import Head from "next/head";

import { Cursor } from "../components/custom-cursor/cursor.component";
import { Header } from "../components/header/header-component";
import { Timer } from "../components/timer/timer-component";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Cursor />
        <Header />
        <Timer />
      </main>
    </>
  );
}
